import type { TapInventorySiteConfig } from "./tap-inventory-client";

export const UPULLITNE_SITE_CONFIG: TapInventorySiteConfig<"upullitne"> = {
  source: "upullitne",
  siteName: "U Pull-It Nebraska",
  baseUrl: "https://upullitne.com",
  inventoryPageUrl: "https://upullitne.com/search-inventory/",
  ajaxUrl: "https://upullitne.com/wp-admin/admin-ajax.php",
  pluginUrl:
    "https://upullitne.com/wp-content/plugins/tap-inventory-search-system/",
  expectedPluginPath: "tap-inventory-search-system",
  partsPricelistPath: "/parts-pricelist/",
  storeLocations: {
    LINCOLN: {
      code: "LINCOLN",
      locationName: "U Pull-It Nebraska - Lincoln",
      city: "Lincoln",
      state: "Nebraska",
      stateAbbr: "NE",
      zipCode: "68507",
      phone: "402-467-4101",
      address: "6300 N. 70th Street",
      lat: 40.8715,
      lng: -96.6256,
    },
    "OMAHA NORTH": {
      code: "OMAHA NORTH",
      locationName: "U Pull-It Nebraska - Omaha North",
      city: "Omaha",
      state: "Nebraska",
      stateAbbr: "NE",
      zipCode: "68110",
      phone: "402-342-0831",
      address: "1405 Grace Street",
      lat: 41.2801,
      lng: -95.9658,
    },
    "OMAHA SOUTH": {
      code: "OMAHA SOUTH",
      locationName: "U Pull-It Nebraska - Omaha South",
      city: "Omaha",
      state: "Nebraska",
      stateAbbr: "NE",
      zipCode: "68117",
      phone: "402-734-6029",
      address: "5600 S. 60th Street",
      lat: 41.2042,
      lng: -96.0011,
    },
    "DES MOINES": {
      code: "DES MOINES",
      locationName: "U Pull-It Nebraska - Des Moines",
      city: "Des Moines",
      state: "Iowa",
      stateAbbr: "IA",
      zipCode: "50313",
      phone: "515-528-3600",
      address: "1600 NE 44th Ave",
      lat: 41.6387,
      lng: -93.5566,
    },
  },
  makes: [
    "ACURA",
    "AUDI",
    "BMW",
    "BUICK",
    "CADILLAC",
    "CHEVROLET",
    "CHRYSLER",
    "DODGE",
    "FIAT",
    "FORD",
    "GEO",
    "GMC",
    "HONDA",
    "HUMMER",
    "HYUNDAI",
    "INFINITI",
    "ISUZU",
    "JAGUAR",
    "JEEP",
    "KIA",
    "LAND ROVER",
    "LEXUS",
    "LINCOLN",
    "MAZDA",
    "MERCEDES-BENZ",
    "MERCURY",
    "MINI",
    "MITSUBISHI",
    "NISSAN",
    "OLDSMOBILE",
    "PLYMOUTH",
    "PONTIAC",
    "SAAB",
    "SATURN",
    "SCION",
    "SUBARU",
    "SUZUKI",
    "TOYOTA",
    "VOLKSWAGEN",
    "VOLVO",
  ],
};

export const TEARAPART_SITE_CONFIG: TapInventorySiteConfig<"tearapart"> = {
  source: "tearapart",
  siteName: "Tear-A-Part",
  baseUrl: "https://tearapart.com",
  inventoryPageUrl: "https://tearapart.com/inventory/",
  ajaxUrl: "https://tearapart.com/wp-admin/admin-ajax.php",
  pluginUrl:
    "https://tearapart.com/wp-content/plugins/tap-inventory-search-system/",
  expectedPluginPath: "tap-inventory-search-system",
  partsPricelistPath: "/price-list/",
  storeLocations: {
    "SALT LAKE CITY": {
      code: "SALT LAKE CITY",
      locationName: "Tear-A-Part - Salt Lake City",
      city: "Salt Lake City",
      state: "Utah",
      stateAbbr: "UT",
      zipCode: "84104",
      phone: "801-886-2345",
      address: "652 S. Redwood Rd",
      lat: 40.7535,
      lng: -111.94,
    },
    OGDEN: {
      code: "OGDEN",
      locationName: "Tear-A-Part - Ogden",
      city: "Ogden",
      state: "Utah",
      stateAbbr: "UT",
      zipCode: "84404",
      phone: "801-564-6960",
      address: "763 W 12th St",
      lat: 41.2437,
      lng: -112.0035,
    },
  },
  makes: [
    "ACURA",
    "AUDI",
    "BMW",
    "BUICK",
    "CADILLAC",
    "CHEVROLET",
    "CHRYSLER",
    "DODGE",
    "FIAT",
    "FORD",
    "GEO",
    "GMC",
    "HONDA",
    "HYUNDAI",
    "INFINITI",
    "ISUZU",
    "JAGUAR",
    "JEEP",
    "KIA",
    "LAND ROVER",
    "LEXUS",
    "LINCOLN",
    "MAZDA",
    "MERCEDES-BENZ",
    "MERCURY",
    "MG",
    "MINI",
    "MITSUBISHI",
    "NISSAN",
    "OLDSMOBILE",
    "PLYMOUTH",
    "PONTIAC",
    "SAAB",
    "SATURN",
    "SCION",
    "SUBARU",
    "SUZUKI",
    "TOYOTA",
    "VOLKSWAGEN",
    "VOLVO",
  ],
};
